apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cluster-exporter
  labels:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
