apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cluster-exporter
  labels:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/component: exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
  endpoints:
    - port: metrics
      interval: 30s
